#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := gcc
CXX := g++
LD := $(CXX)
AR := ar
OBJCOPY := objcopy

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1
INCLUDE_DIRS := /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/include /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/include/linux
LIBRARY_DIRS := usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/lib /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/arm/client /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/arm/server
LIBRARY_NAMES := espeak jvm
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0 -std=gnu++11
CXXFLAGS := -ggdb -ffunction-sections -O0 -std=gnu++11
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
